name: ci

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        context: [prototypes/casting, prototypes/horde-scale, prototypes/quest-loop, prototypes/essence-casting, prototypes/raid-and-raise, prototypes/slab, prototypes/crypt, prototypes/graveshift]
    uses: Kautiontape/ci/.github/workflows/docker-build.yml@main
    with:
      context: ${{ matrix.context }}
